### ISSUE TITLE
Wrong pin_package header file inclusions for some variants.

### ISSUE THREAD

**Issue by gtaska** [cypresssemiconductorco/psoc4hal#1]
**Prerequisites**

Can you reproduce the problem reliably? Yes

Did you check current release notes for known issues? No

If this is not the latest release, have you checked newer releases?  Latest Release

**Description**:

When specifying the part 'CY8C4146LQI-S422', cyhal_pin_pacakage.h includes a header file that doesn't exist for 32-pin QFN parts.

```
#elif defined(_GPIO_PSOC4100S_32_QFN_H_)
#include "pin_packages/cyhal_psoc4100s_24_qfn.h"
```

The correct header file to include should be `cyhal_psoc4100s_32_qfn.h`

I also suspect that the following include file is also incorrect:

```
#elif defined(_GPIO_PSOC4100S_35_WLCSP_H_)
#include "pin_packages/cyhal_psoc4100s_25_wlcsp.h"
```

**Steps to Reproduce:**

1. Create a bsp that targets any 4100S 32-pin QFN-package part.

**Expected Result:**

Correct compilation

**Actual Result:**

```
In file included from ./libs/psoc4hal/COMPONENT_PSOC4HAL/include/cyhal_hw_types.h:82:0,
                 from ./libs/psoc4hal/include/cyhal_gpio.h:87,
                 from ./libs/psoc4hal/COMPONENT_PSOC4HAL/include/cyhal_gpio_impl.h:29,
                 from libs/psoc4hal/COMPONENT_PSOC4HAL/source/cyhal_gpio.c:26:
./libs/psoc4hal/COMPONENT_PSOC4HAL/include/cyhal_pin_package.h:86:10: fatal error: pin_packages/cyhal_psoc4100s_24_qfn.h: No such file or directory
 #include "pin_packages/cyhal_psoc4100s_24_qfn.h"
```

**Frequency (1/1, 1/50, 1/100):**

1/1

**Build/Commit:**

0.5.0.15363

**Target:**

CY8C4146LQI-S422

**Host OS and Version:**

Windows 10/ModusToolbox Shell (Cygwin)

**Compiler:**

ModusToolbox tools_2.1/gcc-7.2.1

**Environment**

N/A

**Comment by rmbk19** [comment]
Hi @gtaska,

Support for PSoC 4 devices is currently in the alpha stage and we have enabled support only for PSoC 4100S Plus device. We will be enabling the support for PSoC 4100S soon. I will provide an update on this issue once it is released.

Thanks and Regards, 
Rakshith M B
